session_name: c-slib-cmake
windows:
  - window_name: editor-project
    shell_command_before:
      - cd ~/Developer/BocanOnlineTemplates/c
      - nvim
  - window_name: shell
    shell_command_before:
      - cd ~/Developer/BocanOnlineTemplates/c
